# Generated by Django 5.0.2 on 2024-04-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_alter_branch_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='short_form',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='slot',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
