# Generated by Django 5.0.2 on 2024-04-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0005_course_short_form_course_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slot',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
