# Generated by Django 5.0.2 on 2024-04-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0006_alter_course_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='last_attendance_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
