# Generated by Django 5.0.2 on 2024-03-04 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academia', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchHoursDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour_1', models.PositiveIntegerField()),
                ('hour_2', models.PositiveIntegerField()),
                ('hour_3', models.PositiveIntegerField()),
                ('hour_4', models.PositiveIntegerField()),
                ('hour_5', models.PositiveIntegerField()),
                ('hour_6', models.PositiveIntegerField()),
                ('hour_7', models.PositiveIntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.branch')),
            ],
        ),
        migrations.CreateModel(
            name='PercentageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_hours_missed', models.PositiveIntegerField()),
                ('percentage_of_subject', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academia.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour_1', models.PositiveIntegerField()),
                ('hour_2', models.PositiveIntegerField()),
                ('hour_3', models.PositiveIntegerField()),
                ('hour_4', models.PositiveIntegerField()),
                ('hour_5', models.PositiveIntegerField()),
                ('hour_6', models.PositiveIntegerField()),
                ('hour_7', models.PositiveIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.students')),
            ],
        ),
    ]
