# Generated by Django 5.0.2 on 2024-03-04 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='percentagedetails',
            name='course',
        ),
        migrations.AddField(
            model_name='percentagedetails',
            name='branch',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='academia.branch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branchhoursdetails',
            name='hour_1',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
        migrations.AlterField(
            model_name='branchhoursdetails',
            name='hour_2',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
        migrations.AlterField(
            model_name='branchhoursdetails',
            name='hour_3',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
        migrations.AlterField(
            model_name='branchhoursdetails',
            name='hour_4',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
        migrations.AlterField(
            model_name='branchhoursdetails',
            name='hour_5',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
        migrations.AlterField(
            model_name='branchhoursdetails',
            name='hour_6',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
        migrations.AlterField(
            model_name='branchhoursdetails',
            name='hour_7',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='hour_1',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='hour_2',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='hour_3',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='hour_4',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='hour_5',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='hour_6',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='hour_7',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
    ]
