# Generated by Django 5.0.2 on 2024-03-08 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_branch_excel_file'),
        ('attendance', '0002_remove_percentagedetails_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='percentagedetails',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='percentagedetails',
            name='number_of_hours_missed',
        ),
        migrations.AddField(
            model_name='percentagedetails',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academia.course'),
        ),
        migrations.AddField(
            model_name='percentagedetails',
            name='hours_lost_with_duty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='percentagedetails',
            name='hours_lost_without_duty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='duty_hour_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='duty_hour_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='duty_hour_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='duty_hour_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='duty_hour_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='duty_hour_6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='duty_hour_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='percentagedetails',
            name='percentage_of_subject',
            field=models.FloatField(default=100),
        ),
    ]
