# Generated by Django 5.0.2 on 2024-03-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_branchhoursdetails_hour_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchhoursdetails',
            name='hour_1',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
        migrations.AlterField(
            model_name='branchhoursdetails',
            name='hour_2',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
        migrations.AlterField(
            model_name='branchhoursdetails',
            name='hour_3',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
        migrations.AlterField(
            model_name='branchhoursdetails',
            name='hour_4',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
        migrations.AlterField(
            model_name='branchhoursdetails',
            name='hour_5',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
        migrations.AlterField(
            model_name='branchhoursdetails',
            name='hour_6',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
        migrations.AlterField(
            model_name='branchhoursdetails',
            name='hour_7',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='hour_1',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='hour_2',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='hour_3',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='hour_4',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='hour_5',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='hour_6',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='hour_7',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
    ]
