# Generated by Django 5.0.2 on 2024-03-17 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_alter_studentattendance_hour_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchHoursDetailsModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_by_admin', models.BooleanField(default=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('branch_hours_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.branchhoursdetails')),
            ],
        ),
        migrations.AddField(
            model_name='branchhoursdetails',
            name='modification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.branchhoursdetailsmodification'),
        ),
    ]
