# Generated by Django 5.0.2 on 2024-03-17 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_alter_branchhoursdetails_modification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchhoursdetails',
            name='modification',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.branchhoursdetailsmodification'),
        ),
    ]
