# Generated by Django 5.0.2 on 2024-03-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_alter_branchhoursdetails_modification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchhoursdetails',
            name='modification',
        ),
        migrations.AddField(
            model_name='branchhoursdetails',
            name='modified_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='BranchHoursDetailsModification',
        ),
    ]
