# Generated by Django 5.0.2 on 2024-03-17 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_remove_branchhoursdetails_modification_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchhoursdetails',
            old_name='modified_by_admin',
            new_name='null_values_intentional',
        ),
    ]
