# Generated by Django 5.0.2 on 2024-03-17 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_rename_modified_by_admin_branchhoursdetails_null_values_intentional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchhoursdetails',
            name='null_values_intentional',
        ),
    ]
