# Generated by Django 5.0.2 on 2024-03-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_remove_branchhoursdetails_null_values_intentional'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchhoursdetails',
            name='finished_marking',
            field=models.BooleanField(default=False),
        ),
    ]
